readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (oyster.df)
readline("Press <Enter> to continue:")
attach(oyster.df)
readline("Press <Enter> to continue:")
Site<-factor(Site)
readline("Press <Enter> to continue:")
boxplot(Oysters~Site,ylab="Number of Oysters",main="Boxplot of Oysters by Site")
readline("Press <Enter> to continue:")
oyster.fit<-lm(Oysters~Site)
readline("Press <Enter> to continue:")
eovcheck (oyster.fit)
readline("Press <Enter> to continue:")
log.Oysters<-log(Oysters)
readline("Press <Enter> to continue:")
oyster.fit1<-lm(log.Oysters~Site)
readline("Press <Enter> to continue:")
eovcheck (oyster.fit1)
readline("Press <Enter> to continue:")
normcheck (oyster.fit1)
readline("Press <Enter> to continue:")
summary1way(oyster.fit1)
readline("Press <Enter> to continue:")
multipleComp(oyster.fit1)
readline("Press <Enter> to continue:")
detach(oyster.df)
readline("Press <Enter> to continue:")
par (opar)
