readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (soya.df)
readline("Press <Enter> to continue:")
attach(soya.df)
readline("Press <Enter> to continue:")
soya.df
readline("Press <Enter> to continue:")
interactionPlots(yield~cultivar+planttime)
readline("Press <Enter> to continue:")
interactionPlots(yield~planttime+cultivar)
readline("Press <Enter> to continue:")
soya.fit<-lm(yield~cultivar+planttime+cultivar*planttime)
readline("Press <Enter> to continue:")
eovcheck (soya.fit)
readline("Press <Enter> to continue:")
normcheck (soya.fit)
readline("Press <Enter> to continue:")
summary2way(soya.fit,page="table")
readline("Press <Enter> to continue:")
summary2way(soya.fit,page="effects")
readline("Press <Enter> to continue:")
summary2way(soya.fit,page="means")
readline("Press <Enter> to continue:")
summary2way(soya.fit,page="nointeraction")
readline("Press <Enter> to continue:")
detach(soya.df)
readline("Press <Enter> to continue:")
par (opar)
