readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (arousal.df)
readline("Press <Enter> to continue:")
attach(arousal.df)
readline("Press <Enter> to continue:")
arousal.df
readline("Press <Enter> to continue:")
interactionPlots(arousal~picture+gender)
readline("Press <Enter> to continue:")
interactionPlots(arousal~gender+picture)
readline("Press <Enter> to continue:")
arousal.fit<-lm(arousal~gender+picture+gender*picture)
readline("Press <Enter> to continue:")
eovcheck (arousal.fit)
readline("Press <Enter> to continue:")
normcheck (arousal.fit)
readline("Press <Enter> to continue:")
summary2way(arousal.fit,page="table")
readline("Press <Enter> to continue:")
summary2way(arousal.fit,page="interaction")
readline("Press <Enter> to continue:")
gender.picture<-crossFactors(gender,picture)
readline("Press <Enter> to continue:")
gender.picture<-factor(gender.picture)
readline("Press <Enter> to continue:")
arousal.1way.fit<-lm(arousal~gender.picture)
readline("Press <Enter> to continue:")
summary1way(arousal.1way.fit)
readline("Press <Enter> to continue:")
multipleComp(arousal.1way.fit)
readline("Press <Enter> to continue:")
par (opar)
