readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (diamonds.df)
readline("Press <Enter> to continue:")
diamonds.df
readline("Press <Enter> to continue:")
attach(diamonds.df)
readline("Press <Enter> to continue:")
plot(price~weight,main="Price versus weight of diamonds")
readline("Press <Enter> to continue:")
diamond.fit<-lm(price~weight)
readline("Press <Enter> to continue:")
eovcheck (diamond.fit)
readline("Press <Enter> to continue:")
summary(diamond.fit)
readline("Press <Enter> to continue:")
layout20x(1,2)
readline("Press <Enter> to continue:")
plot(diamond.fit,which=1)
readline("Press <Enter> to continue:")
plot(residuals(diamond.fit)~weight,main="Residual plot (weight)")
readline("Press <Enter> to continue:")
normcheck (diamond.fit)
readline("Press <Enter> to continue:")
ciReg(diamond.fit)
readline("Press <Enter> to continue:")
diamond.predict<-data.frame(c(0.3,1.2))
readline("Press <Enter> to continue:")
predict20x(diamond.fit,diamond.predict)
readline("Press <Enter> to continue:")
detach(diamonds.df)
readline("Press <Enter> to continue:")
par (opar)
