readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (camplake.df)
readline("Press <Enter> to continue:")
attach(camplake.df)
readline("Press <Enter> to continue:")
camplake.df
readline("Press <Enter> to continue:")
trendscatter(Length~Scale.Radius)
readline("Press <Enter> to continue:")
bluegill.fit<-lm(Length~Scale.Radius)
readline("Press <Enter> to continue:")
eovcheck (bluegill.fit)
readline("Press <Enter> to continue:")
summary(bluegill.fit)
readline("Press <Enter> to continue:")
residPlot(bluegill.fit)
readline("Press <Enter> to continue:")
bluegill.fit1<-lm(Length~Scale.Radius+I(Scale.Radius^2))
readline("Press <Enter> to continue:")
summary(bluegill.fit1)
readline("Press <Enter> to continue:")
residPlot(bluegill.fit1)
readline("Press <Enter> to continue:")
normcheck (bluegill.fit1)
readline("Press <Enter> to continue:")
sr<-seq(1.3,3.6,by=0.01)
readline("Press <Enter> to continue:")
l<-bluegill.fit1$coef[1]+bluegill.fit1$coef[2]*sr+(bluegill.fit1$coef[3]*(sr^2))
readline("Press <Enter> to continue:")
matplot(sr,l,type="l",main="Fitted Model",xlab="Scale.Radius",ylab="Length")
readline("Press <Enter> to continue:")
points(Scale.Radius,Length)
readline("Press <Enter> to continue:")
trendscatter(Length~Age)
readline("Press <Enter> to continue:")
bluegill.fit<-lm(Length~Age)
readline("Press <Enter> to continue:")
eovcheck (bluegill.fit)
readline("Press <Enter> to continue:")
summary(bluegill.fit)
readline("Press <Enter> to continue:")
residPlot(bluegill.fit,f=0.75)
readline("Press <Enter> to continue:")
normcheck (bluegill.fit)
readline("Press <Enter> to continue:")
ciReg(bluegill.fit)
readline("Press <Enter> to continue:")
detach(camplake.df)
readline("Press <Enter> to continue:")
par (opar)
