readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data(bursary.df)
readline("Press <Enter> to continue:")
bursary.df
readline("Press <Enter> to continue:")
attach(bursary.df)
readline("Press <Enter> to continue:")
plot(pass.rate~decile,main="Pass rate versus decile")
readline("Press <Enter> to continue:")
trendscatter(pass.rate~decile,f=0.95)
readline("Press <Enter> to continue:")
bursary.fit<-lm(pass.rate~decile)
readline("Press <Enter> to continue:")
eovcheck (bursary.fit)
readline("Press <Enter> to continue:")
fail.rate<-100-pass.rate
readline("Press <Enter> to continue:")
bursary.fit1<-lm(fail.rate~decile)
readline("Press <Enter> to continue:")
eovcheck (bursary.fit1)
readline("Press <Enter> to continue:")
bursary.fit2<-lm(log(fail.rate)~decile)
readline("Press <Enter> to continue:")
eovcheck (bursary.fit2)
readline("Press <Enter> to continue:")
normcheck (bursary.fit2)
readline("Press <Enter> to continue:")
summary(bursary.fit2)
readline("Press <Enter> to continue:")
exp(ciReg(bursary.fit2))
readline("Press <Enter> to continue:")
detach(bursary.df)
readline("Press <Enter> to continue:")
par (opar)
