readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data(teach.df)
readline("Press <Enter> to continue:")
teach.df
readline("Press <Enter> to continue:")
attach(teach.df)
readline("Press <Enter> to continue:")
plot(lang~IQ,main="Language Score versus IQ (by method)",type="n")
readline("Press <Enter> to continue:")
text(IQ,lang,method)
readline("Press <Enter> to continue:")
method<-factor(method)
readline("Press <Enter> to continue:")
teach.fit<-lm(lang~IQ+method)
readline("Press <Enter> to continue:")
eovcheck (teach.fit)
readline("Press <Enter> to continue:")
summary(teach.fit)
readline("Press <Enter> to continue:")
plot(teach.fit,which=1)
readline("Press <Enter> to continue:")
normcheck (teach.fit)
readline("Press <Enter> to continue:")
ciReg(teach.fit)
readline("Press <Enter> to continue:")
method<-factor(method,levels=c(2,1,3))
readline("Press <Enter> to continue:")
teach.fit1<-lm(lang~IQ+method)
readline("Press <Enter> to continue:")
summary(teach.fit1)
readline("Press <Enter> to continue:")
ciReg(teach.fit1)
readline("Press <Enter> to continue:")
plot(lang~IQ,main="Fitted lines",type="n")
readline("Press <Enter> to continue:")
text(IQ,lang,as.character(method))
readline("Press <Enter> to continue:")
abline(teach.fit$coef[1],teach.fit$coef[2])
readline("Press <Enter> to continue:")
abline(teach.fit$coef[1]+teach.fit$coef[3],teach.fit$coef[2])
readline("Press <Enter> to continue:")
abline(teach.fit$coef[1]+teach.fit$coef[4],teach.fit$coef[2])
readline("Press <Enter> to continue:")
detach(teach.df)
readline("Press <Enter> to continue:")
par (opar)
