readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (camplake.df)
readline("Press <Enter> to continue:")
attach(camplake.df)
readline("Press <Enter> to continue:")
Age.F<-factor(Age)
readline("Press <Enter> to continue:")
plot(Length~Scale.Radius,type="n",main="Length vs Scale radius (by Age)")
readline("Press <Enter> to continue:")
text(Scale.Radius,Length,Age.F)
readline("Press <Enter> to continue:")
bluegill.fit<-lm(Length~Scale.Radius+Age.F)
readline("Press <Enter> to continue:")
eovcheck (bluegill.fit)
readline("Press <Enter> to continue:")
normcheck (bluegill.fit)
readline("Press <Enter> to continue:")
summary(bluegill.fit)
readline("Press <Enter> to continue:")
ciReg(bluegill.fit)
readline("Press <Enter> to continue:")
detach(camplake.df)
readline("Press <Enter> to continue:")
par (opar)
