readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data(peru.df)
readline("Press <Enter> to continue:")
peru.df
readline("Press <Enter> to continue:")
attach(peru.df)
readline("Press <Enter> to continue:")
pairs20x(data.frame(BP,age,years,weight,height))
readline("Press <Enter> to continue:")
peru.fit<-lm(BP~age+years+weight+height)
readline("Press <Enter> to continue:")
eovcheck (peru.fit)
readline("Press <Enter> to continue:")
summary(peru.fit)
readline("Press <Enter> to continue:")
residPlot(peru.fit,f=0.95)
readline("Press <Enter> to continue:")
layout20x(1,2)
readline("Press <Enter> to continue:")
plot(residuals(peru.fit)~years,main="Residual plot (years)")
readline("Press <Enter> to continue:")
lines(lowess(years,residuals(peru.fit),f=0.8))
readline("Press <Enter> to continue:")
plot(residuals(peru.fit)~weight,main="Residual plot (weight)")
readline("Press <Enter> to continue:")
lines(lowess(weight,residuals(peru.fit),f=0.8))
readline("Press <Enter> to continue:")
peru.fit1<-lm(BP~age+years+I(years^2)+weight+height)
readline("Press <Enter> to continue:")
summary(peru.fit1)
readline("Press <Enter> to continue:")
layout20x(1,1)
readline("Press <Enter> to continue:")
residPlot(peru.fit1,f=0.95)
readline("Press <Enter> to continue:")
normcheck (peru.fit1)
readline("Press <Enter> to continue:")
cooks20x(peru.fit1)
readline("Press <Enter> to continue:")
peru.fit2<-lm(BP~age+years+I(years^2)+weight+height,data=peru.df[-1,])
readline("Press <Enter> to continue:")
summary(peru.fit2)
readline("Press <Enter> to continue:")
peru.fit3<-lm(BP~age+years+I(years^2)+weight+height,data=peru.df[-c(1,37),])
readline("Press <Enter> to continue:")
summary(peru.fit3)
readline("Press <Enter> to continue:")
summary(peru.fit1)$coef
readline("Press <Enter> to continue:")
summary(peru.fit2)$coef
readline("Press <Enter> to continue:")
summary(peru.fit3)$coef
readline("Press <Enter> to continue:")
plot(peru.fit3,which=1)
readline("Press <Enter> to continue:")
normcheck (peru.fit3)
readline("Press <Enter> to continue:")
ciReg(peru.fit3)
readline("Press <Enter> to continue:")
yrs<-seq(0,45,by=0.01)
readline("Press <Enter> to continue:")
bp<- -1.76743*yrs+(0.03225*(yrs^2))
readline("Press <Enter> to continue:")
matplot(yrs,bp,type="l",main="BP versus Years",xlab="years",ylab="BP")
readline("Press <Enter> to continue:")
abline(v=27)
readline("Press <Enter> to continue:")
detach(peru.df)
readline("Press <Enter> to continue:")
par (opar)
