readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (camplake.df)
readline("Press <Enter> to continue:")
attach(camplake.df)
readline("Press <Enter> to continue:")
pairs20x(data.frame(Length,Age,Scale.Radius))
readline("Press <Enter> to continue:")
bluegill.fit<-lm(Length~Age+Scale.Radius)
readline("Press <Enter> to continue:")
eovcheck (bluegill.fit)
readline("Press <Enter> to continue:")
bluegill.fit1<-lm(log(Length)~Age+Scale.Radius)
readline("Press <Enter> to continue:")
eovcheck (bluegill.fit1)
readline("Press <Enter> to continue:")
layout20x(1,2)
readline("Press <Enter> to continue:")
plot(residuals(bluegill.fit1)~Age,main="Residual plot (Age)")
readline("Press <Enter> to continue:")
plot(residuals(bluegill.fit1)~Scale.Radius,main="Residual plot (Scale.Radius)")
readline("Press <Enter> to continue:")
bluegill.fit2<-lm(log(Length)~Age+I(Age^2)+Scale.Radius)
readline("Press <Enter> to continue:")
summary(bluegill.fit2)
readline("Press <Enter> to continue:")
layout20x(1,1)
readline("Press <Enter> to continue:")
plot(bluegill.fit2,which=1)
readline("Press <Enter> to continue:")
normcheck (bluegill.fit2)
readline("Press <Enter> to continue:")
cooks20x(bluegill.fit2)
readline("Press <Enter> to continue:")
exp(ciReg(bluegill.fit2))
readline("Press <Enter> to continue:")
detach(camplake.df)
readline("Press <Enter> to continue:")
par (opar)
