readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (course.df)
readline("Press <Enter> to continue:")
course.df
readline("Press <Enter> to continue:")
attach(course.df)
readline("Press <Enter> to continue:")
pairs20x(data.frame(Exam,Assign,Test,Years.Since))
readline("Press <Enter> to continue:")
exam.fit<-lm(Exam~Assign+Test+Stage1+Gender+Attend+ Years.Since+Repeat+Degree)
readline("Press <Enter> to continue:")
eovcheck (exam.fit)
readline("Press <Enter> to continue:")
summary(exam.fit)
readline("Press <Enter> to continue:")
anova(exam.fit)
readline("Press <Enter> to continue:")
exam.fit1<-lm(Exam~Assign+Test+Stage1+Gender+Attend+Years.Since+Repeat)
readline("Press <Enter> to continue:")
summary(exam.fit1)
readline("Press <Enter> to continue:")
exam.fit2<-lm(Exam~Assign+Test+Stage1+Gender+Attend+Repeat)
readline("Press <Enter> to continue:")
summary(exam.fit2)
readline("Press <Enter> to continue:")
exam.fit3<-lm(Exam~Assign+Test+Stage1+Attend+Repeat)
readline("Press <Enter> to continue:")
summary(exam.fit3)
readline("Press <Enter> to continue:")
exam.fit4<-lm(Exam~Assign+Test+Stage1+Repeat)
readline("Press <Enter> to continue:")
summary(exam.fit4)
readline("Press <Enter> to continue:")
exam.fit5<-lm(Exam~Assign+Test+Stage1)
readline("Press <Enter> to continue:")
summary(exam.fit5)
readline("Press <Enter> to continue:")
plot(exam.fit5,which=1)
readline("Press <Enter> to continue:")
layout20x(1,2)
readline("Press <Enter> to continue:")
plot(residuals(exam.fit5)~Assign,main="Residual plot (Assign)")
readline("Press <Enter> to continue:")
lines(lowess(Assign,residuals(exam.fit5)))
readline("Press <Enter> to continue:")
plot(residuals(exam.fit5)~Test,main="Residual plot (Test)")
readline("Press <Enter> to continue:")
lines(lowess(Test,residuals(exam.fit5)))
readline("Press <Enter> to continue:")
layout20x(1,1)
readline("Press <Enter> to continue:")
exam.fit6<-lm(Exam~Assign+Test+I(Test^2)+Stage1)
readline("Press <Enter> to continue:")
summary(exam.fit6)
readline("Press <Enter> to continue:")
plot(exam.fit6,which=1)
readline("Press <Enter> to continue:")
cooks20x(exam.fit6)
readline("Press <Enter> to continue:")
course.df[106,]
readline("Press <Enter> to continue:")
obs<-1:146
readline("Press <Enter> to continue:")
plot(Test~Assign,type="n",main="Test versus Assign")
readline("Press <Enter> to continue:")
text(Assign,Test,obs)
readline("Press <Enter> to continue:")
exam.fit7<-lm(Exam~Assign+Test+I(Test^2)+Stage1,data=course.df[-106,])
readline("Press <Enter> to continue:")
summary(exam.fit7)$coef
readline("Press <Enter> to continue:")
summary(exam.fit6)$coef
readline("Press <Enter> to continue:")
normcheck (exam.fit6)
readline("Press <Enter> to continue:")
ciReg(exam.fit6)
readline("Press <Enter> to continue:")
Stage1<-factor(Stage1,levels=c("B","C","A"))
readline("Press <Enter> to continue:")
exam.fit6a<-lm(Exam~Assign+Test+I(Test^2)+Stage1)
readline("Press <Enter> to continue:")
summary(exam.fit6a)$coef
readline("Press <Enter> to continue:")
ciReg(exam.fit6a)
readline("Press <Enter> to continue:")
test<-seq(4,20,by=0.01)
readline("Press <Enter> to continue:")
exam<- -1.2472*test+(0.13846*(test^2))
readline("Press <Enter> to continue:")
matplot(test,exam,type="l",main="Exam versus Test",xlab="test",ylab="eaxm")
readline("Press <Enter> to continue:")
detach(course.df)
readline("Press <Enter> to continue:")
par (opar)
