readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data(technitron.df)
readline("Press <Enter> to continue:")
technitron.df
readline("Press <Enter> to continue:")
attach(technitron.df)
readline("Press <Enter> to continue:")
pairs(data.frame(salary,yrs.empl,prior.yrs,educ,gender,dept,super))
readline("Press <Enter> to continue:")
pairs20x(data.frame(salary,yrs.empl,prior.yrs, educ,super))
readline("Press <Enter> to continue:")
dept<-factor(dept)
readline("Press <Enter> to continue:")
tech.fit<-lm(salary~yrs.empl+prior.yrs+educ+gender+super+dept)
readline("Press <Enter> to continue:")
eovcheck (tech.fit)
readline("Press <Enter> to continue:")
tech.fit1<-lm(log(salary)~yrs.empl+prior.yrs+educ+gender+super+dept)
readline("Press <Enter> to continue:")
eovcheck (tech.fit1)
readline("Press <Enter> to continue:")
summary(tech.fit1)
readline("Press <Enter> to continue:")
tech.fit2<-lm(log(salary)~yrs.empl+prior.yrs+educ+gender+dept)
readline("Press <Enter> to continue:")
summary(tech.fit2)
readline("Press <Enter> to continue:")
tech.fit3<-lm(log(salary)~yrs.empl+educ+gender+dept)
readline("Press <Enter> to continue:")
summary(tech.fit3)
readline("Press <Enter> to continue:")
plot(tech.fit3,which=1)
readline("Press <Enter> to continue:")
cooks20x(tech.fit3)
readline("Press <Enter> to continue:")
normcheck (tech.fit3)
readline("Press <Enter> to continue:")
exp(ciReg(tech.fit2,cilevel=0.9))
readline("Press <Enter> to continue:")
detach(technitron.df)
readline("Press <Enter> to continue:")
par (opar)
