readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (zoo.df)
readline("Press <Enter> to continue:")
zoo.df
readline("Press <Enter> to continue:")
attach(zoo.df)
readline("Press <Enter> to continue:")
pairs20x(data.frame(attendance,time,sun.yesterday,tv.ads))
readline("Press <Enter> to continue:")
stripchart(attendance~nice.day,vert=T,pch=1,method="jitter",main="Attendance by nice day")
readline("Press <Enter> to continue:")
stripchart(attendance~day.type,vert=T,pch=1,method="jitter",main="Attendance by day type")
readline("Press <Enter> to continue:")
day.type<-factor(day.type)
readline("Press <Enter> to continue:")
zoo.fit<-lm(attendance~time+sun.yesterday+tv.ads+nice.day+ day.type)
readline("Press <Enter> to continue:")
eovcheck (zoo.fit)
readline("Press <Enter> to continue:")
plot(residuals(zoo.fit)~fitted(zoo.fit),type="n",main="Residual plot (fitted) by day type")
readline("Press <Enter> to continue:")
text(fitted(zoo.fit),residuals(zoo.fit),day.type)
readline("Press <Enter> to continue:")
zoo.fit1<-lm(log(attendance)~time+sun.yesterday+tv.ads+ nice.day+day.type)
readline("Press <Enter> to continue:")
plot(residuals(zoo.fit1)~fitted(zoo.fit1),type="n",main="Residual plot (fitted) by day type")
readline("Press <Enter> to continue:")
text(fitted(zoo.fit1),residuals(zoo.fit1),day.type)
readline("Press <Enter> to continue:")
summary(zoo.fit1)
readline("Press <Enter> to continue:")
cooks20x(zoo.fit1)
readline("Press <Enter> to continue:")
normcheck (zoo.fit1)
readline("Press <Enter> to continue:")
exp(ciReg(zoo.fit1))
readline("Press <Enter> to continue:")
detach(zoo.df)
readline("Press <Enter> to continue:")
par (opar)
