readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (apples.df)
readline("Press <Enter> to continue:")
attach (apples.df)
readline("Press <Enter> to continue:")
apples.df
readline("Press <Enter> to continue:")
stripchart (Weight ~ Rootstock, pch = 1, vert = TRUE,
readline("Press <Enter> to continue:")
	main = "Weight by Rootstock", xlab = "Rootstock", ylab = "Weight")
readline("Press <Enter> to continue:")
summaryStats (Weight ~ Rootstock)
readline("Press <Enter> to continue:")
apples.fit = lm (Weight ~ Rootstock)
readline("Press <Enter> to continue:")
eovcheck (apples.fit)
readline("Press <Enter> to continue:")
normcheck (apples.fit)
readline("Press <Enter> to continue:")
summary1way (apples.fit)
readline("Press <Enter> to continue:")
multipleComp (apples.fit)
readline("Press <Enter> to continue:")
par (opar)
