readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (butterfat.df)
readline("Press <Enter> to continue:")
attach (butterfat.df)
readline("Press <Enter> to continue:")
butterfat.df
readline("Press <Enter> to continue:")
interactionPlots (Butterfat ~ Breed + Age)
readline("Press <Enter> to continue:")
interactionPlots (Butterfat ~ Age + Breed)
readline("Press <Enter> to continue:")
butterfat.fit = lm (Butterfat ~ Breed + Age + Breed:Age)
readline("Press <Enter> to continue:")
eovcheck (butterfat.fit)
readline("Press <Enter> to continue:")
normcheck (butterfat.fit)
readline("Press <Enter> to continue:")
log.Butterfat = log (Butterfat)
readline("Press <Enter> to continue:")
butterfat.fit1 = lm (log.Butterfat ~ Breed + Age + Breed:Age)
readline("Press <Enter> to continue:")
eovcheck (butterfat.fit1)
readline("Press <Enter> to continue:")
normcheck (butterfat.fit1)
readline("Press <Enter> to continue:")
summary2way (butterfat.fit1, page = "table")
readline("Press <Enter> to continue:")
summary2way (butterfat.fit1, page = "effects")
readline("Press <Enter> to continue:")
summary2way (butterfat.fit1, page = "means")
readline("Press <Enter> to continue:")
summary2way (butterfat.fit1, page = "nointeraction")
readline("Press <Enter> to continue:")
par (opar)
