readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (sheep.df)
readline("Press <Enter> to continue:")
attach (sheep.df)
readline("Press <Enter> to continue:")
Copper = factor (Copper)
readline("Press <Enter> to continue:")
Cobalt = factor (Cobalt)
readline("Press <Enter> to continue:")
sheep.df
readline("Press <Enter> to continue:")
interactionPlots (Weight ~ Copper + Cobalt)
readline("Press <Enter> to continue:")
interactionPlots (Weight ~ Cobalt + Copper)
readline("Press <Enter> to continue:")
sheep.fit = lm (Weight ~ Copper + Cobalt + Copper:Cobalt)
readline("Press <Enter> to continue:")
eovcheck (sheep.fit)
readline("Press <Enter> to continue:")
normcheck (sheep.fit)
readline("Press <Enter> to continue:")
summary2way (sheep.fit, page = "table")
readline("Press <Enter> to continue:")
summary2way (sheep.fit, page = "effects")
readline("Press <Enter> to continue:")
summary2way (sheep.fit, page = "means")
readline("Press <Enter> to continue:")
summary2way (sheep.fit, page = "nointeraction")
readline("Press <Enter> to continue:")
par (opar)
