readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (incomes.df)
readline("Press <Enter> to continue:")
attach(incomes.df)
readline("Press <Enter> to continue:")
incomes
readline("Press <Enter> to continue:")
layout20x(1,2)
readline("Press <Enter> to continue:")
hist(incomes)
readline("Press <Enter> to continue:")
boxplot(incomes,main="Boxplot of Incomes")
readline("Press <Enter> to continue:")
summaryStats(incomes)
readline("Press <Enter> to continue:")
normcheck (incomes)
readline("Press <Enter> to continue:")
t.test(incomes)
readline("Press <Enter> to continue:")
trans.incomes<-log(incomes)
readline("Press <Enter> to continue:")
layout20x(1,3)
readline("Press <Enter> to continue:")
qqnorm(trans.incomes)
readline("Press <Enter> to continue:")
abline(mean(trans.incomes),sd(trans.incomes))
readline("Press <Enter> to continue:")
hist(trans.incomes)
readline("Press <Enter> to continue:")
boxplot(trans.incomes,main="Boxplot of trans.incomes")
readline("Press <Enter> to continue:")
summaryStats(trans.incomes)
readline("Press <Enter> to continue:")
normcheck (trans.incomes)
readline("Press <Enter> to continue:")
t.test(trans.incomes)
readline("Press <Enter> to continue:")
c.i.<-t.test(trans.incomes)$conf.int
readline("Press <Enter> to continue:")
c.i.
readline("Press <Enter> to continue:")
exp(c.i.)
readline("Press <Enter> to continue:")
layout20x(1,1)
readline("Press <Enter> to continue:")
detach(incomes.df)
readline("Press <Enter> to continue:")
par (opar)
