readline("Press <Enter> to continue:")
opar = par (ask = dev.interactive (orNone = TRUE) )
readline("Press <Enter> to continue:")
data (cloudseeding.df)
readline("Press <Enter> to continue:")
attach(cloudseeding.df)
readline("Press <Enter> to continue:")
layout20x(1,2)
readline("Press <Enter> to continue:")
stripchart(rain~seed,pch=1,vert=T,ylab="rain",main= "Stripcharts of Seeding")
readline("Press <Enter> to continue:")
boxplot(rain~seed,ylab="rain",main="Boxplots of Seeding")
readline("Press <Enter> to continue:")
summaryStats(rain~seed)
readline("Press <Enter> to continue:")
cloud.fit1 = lm (rain ~ seed)
readline("Press <Enter> to continue:")
eovcheck (cloud.fit1)
readline("Press <Enter> to continue:")
log.rain = log (rain)
readline("Press <Enter> to continue:")
cloud.fit2 = lm (log.rain ~ seed)
readline("Press <Enter> to continue:")
eovcheck (cloud.fit2)
readline("Press <Enter> to continue:")
normcheck (cloud.fit2)
readline("Press <Enter> to continue:")
summary1way (cloud.fit2)
readline("Press <Enter> to continue:")
multipleComp (cloud.fit2)
readline("Press <Enter> to continue:")
summary (cloud.fit2)
readline("Press <Enter> to continue:")
t.test(log.rain~seed,var.equal=T)
readline("Press <Enter> to continue:")
c.i.<-t.test(log.rain~seed,var.equal=T)$conf.int
readline("Press <Enter> to continue:")
c.i.
readline("Press <Enter> to continue:")
exp(c.i.)
readline("Press <Enter> to continue:")
par (opar)
